controller:
  region: 'us-east-1'
sidecars:
  provisioner:
    additionalArgs:
      - --timeout=60s
      - --retry-interval-start=4s
  attacher:
    additionalArgs: 
      - --timeout=60s
      - --retry-interval-start=4s
storageClasses:
  - name: ebs-sc
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    parameters:
      type: <EBS_ALIAS>
volumeSnapshotClasses: 
  - name: ebs-vsc
    annotations:
      snapshot.storage.kubernetes.io/is-default-class: "true"
      k10.kasten.io/is-snapshot-class: "true"
    deletionPolicy: Delete
